### ISSUE TITLE
Slightly confusing description

### ISSUE THREAD

**Issue by alphapapa** [dieggsy/difflib.el#4]
Hi,

I was excited when I saw this library listed as "Helpers for computing deltas between objects," but I was slightly disappointed when I saw that it's only for strings.  To me, "objects" sounds like it means lists, vectors, conses, alists, plists, hash-tables, EIEIO objects, etc.  It might be good if you made the package description more specific.  :)

**Comment by dieggsy** [comment]
@alphapapa it should not only be for strings. If this is the case, that's a bug. Can you tell me what isn't working?

**Comment by dieggsy** [comment]
To clarify, it should work with _sequences_ - which I'll admit I could update in the description - the "Helpers for computing deltas between obects" language comes from the original library's description.

**Comment by dieggsy** [comment]
Additionally, the first sentence of `difflib-sequence-matcher`'s documentation states as much (even though that too is copied from the original library).

**Comment by alphapapa** [comment]
Ok, thanks.  From the examples in the readme, it appears to only handle strings.  If it had some examples of lists of other types (numbers, symbols, other lists, etc), it would help.
