### ISSUE TITLE
Docstring of difflib-unified-diff is truncated

### ISSUE THREAD

**Issue by xuchunyang** [dieggsy/difflib.el#5]
https://github.com/dieggsy/difflib.el/blob/850bfe991cec541d43127c48486bbd5f9c60b359/difflib.el#L743

the empty string `""` should be escaped, i.e., `\"\"`.

**Comment by dieggsy** [comment]
Good catch - those docstrings where outdated anyway :). Fixed in https://github.com/dieggsy/difflib.el/commit/b08850251812d71e62fd6956081299590acdf37b
